### ISSUE TITLE
disabling 'full entry on' option doesn't save 

### ISSUE THREAD

**Issue by katrinleinweber** [gutobenn/wp-to-diaspora#11]
In the WordPress instance I am working on, this option is always enabled. Disabling it and saving enables it again. I'm not sure unfortunately, whether this bug was present, or was introduced by one of the last updates, sorry.

> PHP Version         5.4.36-0+deb7u3
> WordPress Version   4.1
> curl Version        7.26.0

**Comment by gutobenn** [comment]
What's WP to Diáspora version? If not 1.2.4, could you update it and test again?

**Comment by gutobenn** [comment]
Thanks for reporting! Upgrade will be available in some minutes.

**Comment by gutobenn** [comment]
@katrinleinweber Thanks for reporting. Update will be available in some minutes.

**Comment by katrinleinweber** [comment]
Yep, fixed, thank you! How about you create a [Flattr](http://flattr.com/) account or BitCoin address or something, so that people can donate for your project ;-)

**Comment by gutobenn** [comment]
Good suggestion. Added it to README :)
