### ISSUE TITLE
Gallery tag needs attention

### ISSUE THREAD

**Issue by noplanman** [gutobenn/wp-to-diaspora#138]
Posts with a `[gallery ...]` tag just post the tag as is.

@gutobenn What shall we do with these situations? Just show the first image? Not show anything at all? Show them all?

Example posts here: https://pod.geraspora.de/people/069d2f30bb64013258944860008dbc6c

**Comment by gutobenn** [comment]
Showing all the images will probably make posts very long. Between showing one image and not showing any, I prefer the first because then the post get illustrated.

**Comment by noplanman** [comment]
Hmm, I've tested this and for me the gallery gets rendered properly. Thought as much, would have been weird to miss that!

I think that user either disables the `gallery` filter or is on a very old version of WP2D.

@gutobenn We can safely let this one go 👍 

(if it should pop up again, I'll create a new issue with more details)
