### ISSUE TITLE
Admin notice after posting (or trying to) on diaspora

### ISSUE THREAD

**Issue by gutobenn** [gutobenn/wp-to-diaspora#19]
Error messages should be displayed as an admin notice. In case of success, URL of post might be returned.

**Comment by noplanman** [comment]
If the Diaspora* post URL *is* returned, it would make sense to save it to the meta data of the post.
This would make it easier to see that a certain post has already been posted to D*.

**Comment by gutobenn** [comment]
Great! Thanks for implementing it @noplanman :)
