### ISSUE TITLE
Change "Post to Diaspora" radio buttons to checkbox

### ISSUE THREAD

**Issue by gutobenn** [gutobenn/wp-to-diaspora#20]
![screenshot-2](https://cloud.githubusercontent.com/assets/607762/5963801/7eb35bea-a7d6-11e4-8541-2fde8b784e27.png)

Checkbox would be more clear.

**Comment by noplanman** [comment]
Yes, I agree.
Maybe we could also implement some simple JavaScript to make this more dynamic.
So when checking the box, other options get displayed or hidden.

It might make sense to change the title of the MetaBox to "WP to Diaspora*" (like the plugin name) and then have the checkbox with a label of "Post to Diaspora*". Yes?

**Comment by gutobenn** [comment]
Yes!

**Comment by gutobenn** [comment]
Fixed with f0b0753.

**Comment by noplanman** [comment]
The post gets posted on D*, if the checkbox is checked or not.
There's still a small issue here, I'll fix it.
