### ISSUE TITLE
Add hashtags on diaspora post

### ISSUE THREAD

**Issue by gutobenn** [gutobenn/wp-to-diaspora#21]
> Hashtags are an important part of Diaspora posts. I'd like to suggest adding the tags of an article to the end of the post in Diaspora, at the very end.
https://wordpress.org/support/topic/suggestion-add-article-tags-as-hashtags

**Comment by gutobenn** [comment]
Sometimes not all the tags used in a blog post are relevant for posts on diaspora. What about adding a new field for tags?

**Comment by noplanman** [comment]
Great idea!

Maybe a checkbox?
Use the same tags as the post itself *-or-* Define custom tags.

**Comment by gutobenn** [comment]
Yes, seems good.

**Comment by noplanman** [comment]
I thought it would make sense to have a global setting where default tags can be set, which can be added to every post if wanted. e.g. Somebody wants to tag all the posts being shared to Diaspora* with a certain tag, to keep track and let others find those posts easily.

On each individual post, I think the best option would be a dropdown menu, something like this:
* All tags (global, custom and this post)
* Global and this post's tags
* Only this post's tags
* Global and custom tags (default)
* Only custom tags
* No tags

What do you think?

It will be accompanied by a text field, to add the custom tags.

**Comment by gutobenn** [comment]
Great, I liked it! :)

**Comment by gutobenn** [comment]
Thanks you for implementing it, @noplanman! :)
