### ISSUE TITLE
broken preview-link

### ISSUE THREAD

**Issue by steffenster** [gutobenn/wp-to-diaspora#24]
The URL to create the preview is broken or somethink like that. Here is the result: https://pod.geraspora.de/posts/3204619

**Comment by ciubotaru** [comment]
This is a bug in diaspora.

To make a text bold, this plugin adds 2 asterisks at the beginning and 2 at the end of the selected text.

Diaspora understands that the asterisks are for formatting and treats them properly, when displaying text. However, when creating the preview, it ignores the closing ones, so the closing bracket and the last two asterisks appear as part of the link. This makes it point to a different (non-existent) location. Hence broken preview.

**Comment by steffenster** [comment]
Ok, I seperated headline text and URL in my plugin code. [result](https://pod.geraspora.de/posts/3206009)

**Comment by steffenster** [comment]
Even better, I added a title-tag, so it works. [result](https://pod.geraspora.de/posts/3206037)

line 72 in wp-to-diaspora.php
$status_message = "<p><b><a href='" . get_permalink($post_id) . "' title='{$post->post_title}'>{$post->post_title}</a></b></p>";

**Comment by gutobenn** [comment]
Merged. Thanks, Steffen! :)
