### ISSUE TITLE
Enhance UI and UX with jQuery Chosen

### ISSUE THREAD

**Issue by noplanman** [gutobenn/wp-to-diaspora#27]
Use Chosen to prettify the Settings and make it more user friendly.
https://harvesthq.github.io/chosen/

Settings that could benefit from this:
- Pod
- Post types
- Tags to post
- Aspects

**Comment by gutobenn** [comment]
For tags we could use something like this http://aehlke.github.io/tag-it/

**Comment by noplanman** [comment]
Cool, I like those tags!
I'm sure it would possible to modify it to have the same look and feel like Chosen.
