### ISSUE TITLE
i18n for SOV languages

### ISSUE THREAD

**Issue by ciubotaru** [gutobenn/wp-to-diaspora#3]
This line

    __("Connected to", 'wp_to_diaspora') . ' ' . $options['pod'],

will not work well in Subject-Object-Verb languages (e.g. Japanese), where the object ($options['pod']) stands __before__ the verb ("connected"). Consider replacing it with smth like

    printf( __("Connected to %s", 'wp_to_diaspora'), $options['pod']),

P.S.: Explanation here: http://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders

**Comment by ciubotaru** [comment]
Update: I've just read your comment on Poeditor. It's the same problem :-)

**Comment by gutobenn** [comment]
Fixed

**Comment by ciubotaru** [comment]
> Fixed

Not really. You updated the php file and the .po/.mo files, without updating the .pot file. This won't work.

P.S.: Let me share my workflow:
* Make changes in .php.
* Regenerate the .pot file as per [this](http://codex.wordpress.org/I18n_for_WordPress_Developers#Using_the_i18n_tools) howto.
* Upload the .pot to Poeditor.
* Update/review translations.
* Export/download .mo files from Poeditor (separately for each language).
* Test on my blog.
* Release :-)

**Comment by gutobenn** [comment]
Whoops. Now it must be correct.
Thanks by the workflow :)

**Comment by gutobenn** [comment]
Whoops. Now it must be correct.
Thanks by the workflow :)
