### ISSUE TITLE
Conflict in class name

### ISSUE THREAD

**Issue by ciubotaru** [gutobenn/wp-to-diaspora#4]
I tried to install this plugin (from WP Plugin Directory), but received the following error:

    Plugin could not be activated because it triggered a fatal error.
    Fatal error: Cannot redeclare class Diasphp in [...]/wp-content/plugins/wp-to-diaspora/class-diaspora.php on line 9

This is because another plugin is using the same class name. The conflicting plugin is https://github.com/Faldrian/WP-diaspora-postwidget. By coincidence (?), both plugins have a class called "Diasphp"...

**Comment by gutobenn** [comment]
Fixed. No coincidence, they use the same class. 
Idea for newer versions: maybe implementing this plugin in OOP, using classes and namespaces would be a better solution.
