### ISSUE TITLE
Couldn't connect to "https://diasp.org": Failed to initialise connection to pod "https://diasp.org".

### ISSUE THREAD

**Issue by lpar** [gutobenn/wp-to-diaspora#48]
Any idea how I can work out what exactly the error is that's causing this?

Version 1.3.1.

**Comment by gutobenn** [comment]
Hi @lpar

You can activate debugger by adding a ```&debugging``` at the end of settings page URL (like ```http://yourweb.site/wp-admin/options-general.php?page=wp_to_diaspora&debugging```)

**Comment by lpar** [comment]
20150401140049 - WP2D_Options->admin_options_page[class-options.php:117]
    WP2D_API->init[class-options.php:117]
    WP2D_API->_fetch_token[class-api.php:175]
    WP2D_API->_http_request[class-api.php:195]
    WP2D_Helpers::add_debugging[class-api.php:450]
    code 0 on https://diasp.org/users/sign_in

**Comment by ToeiRei** [comment]
Pretty much the same issue here. Debug info as follows:
```
20150423164333 - WP2D_Options->admin_options_page[class-options.php:117]
WP2D_API->init[class-options.php:117]
WP2D_API->_fetch_token[class-api.php:175]
WP2D_API->_http_request[class-api.php:195]
WP2D_Helpers::add_debugging[class-api.php:450]
code 200 on https://pusteblume.stargazer.at/users/sign_in
```

**Comment by gutobenn** [comment]
Is it happening since WP 4.1.2?

**Comment by ToeiRei** [comment]
I cannot confirm that as I got the plugin since I have 4.2-RC1

**Comment by noplanman** [comment]
Please follow the Issue #49 as it's about the same / similar problem, thanks.

**Comment by lpar** [comment]
The fix in #49 doesn't seem to work for me, with WordPress 4.2.

**Comment by noplanman** [comment]
@lpar Please update to 1.3.2 and try again. You will need to re-enter your password and save the settings. I've tested it with ´diasp.org´ and have no problems on my side.
If it still doesn't work, could you attach the debug output again please, thanks! :-)

**Comment by lpar** [comment]
20150424223210 - WP2D_Options->admin_options_page[class-options.php:117]
WP2D_API->init[class-options.php:117]
WP2D_API->_fetch_token[class-api.php:175]
WP2D_API->_http_request[class-api.php:195]
WP2D_Helpers::add_debugging[class-api.php:450]
code 0 on https://diasp.org/users/sign_in

**Comment by noplanman** [comment]
Has the plugin worked for you before or never?
What PHP version are you on and do you have the cURL extension installed?

**Comment by lpar** [comment]
PHP version is 5.3.27.

Running

    <?php
    echo 'Curl: ', function_exists('curl_version') ? 'Enabled: ' + curl_version() : 'Disabled';
    ?>

reports that curl is enabled. The test code at http://php.net/manual/en/function.curl-version.php reports 

    CURL_VERSION_IPV6 matches
    CURL_VERSION_KERBEROS4 does not match
    CURL_VERSION_SSL matches
    CURL_VERSION_LIBZ matches

The plugin has never worked for me.

**Comment by noplanman** [comment]
It's strange that you get a HTTP exit code 0, could be a connection timeout.

In the file `lib/class-api.php` add this line:
`curl_setopt( $ch, CURLOPT_CONNECTTIMEOUT, 20 );`
after line 393:
`$ch = curl_init( $url );`

Does this solve the problem? If not, I need more time to see what the issue could be.

**Comment by lpar** [comment]
Doesn't make any difference.

I can debug things at the command line if that helps. I just checked that command line curl can fetch https://diasp.org/users/sign_in for example.

**Comment by noplanman** [comment]
You could also try:
`curl_setopt( $ch, CURLOPT_VERBOSE, 1 );`

This should give you more info about the connection.

It would be great if you could help to find the problem here, cause I have no problems at all and honestly don't know where to look at the moment...

Take a look at this, maybe it will help to shed some light: http://stackoverflow.com/a/26611776

Thanks for your effort to help resolve this! :-)

**Comment by lpar** [comment]
Aha!

    * About to connect() to diasp.org port 443 (#0)
    *   Trying 173.233.93.6...
    * connected
    * Connected to diasp.org (173.233.93.6) port 443 (#0)
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: none
    * SSL certificate problem, verify that the CA cert is OK. Details:
    error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
    * Closing connection #0

If I add `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);` suddenly it works. But obviously this isn't ideal; the real answer is probably that the code should use `curl_setopt($ch, CURLOPT_CAINFO, "PATH_TO/cacert.pem");` to set PHP to use a CA bundle included with the plugin, I think.

**Comment by noplanman** [comment]
Hmm, interesting find.

But why are you the only one so far to have those issues? The path in `CAfile` is on your server, right?

When you say bundle a CA with the plugin, which one are you talking about? Each pod will have their own one...

Could you maybe explain a bit further what you think could work, I'm sorry I don't totally understand yet.

**Comment by lpar** [comment]
In general, curl doesn't ship with a CA bundle. By default it'll look for one at a path on the server that commonly has one on Linux systems, but there's no guarantee that any other package will have installed a CA bundle there. In the case of my host, no package has. So in general, if you want it to be reliable, you need to ship a CA bundle, or tell the user how to install one.

http://curl.haxx.se/docs/sslcerts.html

**Comment by ciubotaru** [comment]
> the real answer is probably that the code should use curl_setopt($ch, CURLOPT_CAINFO, "PATH_TO/cacert.pem");

I might be missing something very important, but...

Plugin developers have no realistic way to know how blog admins configured their servers. Actually, the blog admins don't know it either, unless they self-host their blogs. So it boils down to this: a misconfigured curl is the problem of the host server.

**Comment by lpar** [comment]
> Plugin developers have no realistic way to know how blog admins configured their servers.

Which is why I suggest the plugin should include a CA bundle, and not just assume that the server will have a suitable one deployed at the path PHP curl looks in as a last resort.

It's also entirely possible that the system will have a CA bundle that can't verify the user's Diaspora* server's cert (e.g. if the Diaspora pod is using a self-signed cert), so at a minimum the plugin code should have an easy way to override the CA bundle.

**Comment by noplanman** [comment]
I've opened up a new issue regarding the SSL certificate situation.
We'll carry on the discussion there: #54
