### ISSUE TITLE
Failed to post to diaspora*: Not logged in. Ignore

### ISSUE THREAD

**Issue by schnied** [gutobenn/wp-to-diaspora#49]
hey, 

most time the plugin works fine. now i get this error when i publish in wordpress:

Failed to post to diaspora*: Not logged in. Ignore

in the plugin settings page i get this error:

Couldn't connect to "https://pod.sd.vc": 

when i add the "&debugging" parameter, this is shown:

---
    20150422154238 - WP2D_Options->admin_options_page[class-options.php:117]
    WP2D_API->init[class-options.php:117]
    WP2D_API->_fetch_token[class-api.php:175]
    WP2D_API->_http_request[class-api.php:195]
    WP2D_Helpers::add_debugging[class-api.php:450]
    code 200 on https://pod.sd.vc/users/sign_in
---
the pod https://pod.sd.vc is up and reachable and i can use it with a brwoser.
(the servers are in the same subnet etc.)

any ideas? 

regards
stefan

**Comment by gutobenn** [comment]
Is it happening since WP 4.1.2?

**Comment by schnied** [comment]
I'm not sure... It could be possible

**Comment by noplanman** [comment]
I'm not yet 100% sure why this issue has started happening, but I think I've managed to hunt it down.

Try editing the `lib/class-helpers.php` file and replace the following lines:
91: `return $wpdb->get_var( $wpdb->prepare( "SELECT HEX(AES_ENCRYPT(%s,%s))", $input, $key ) );`
103: `return $wpdb->get_var( $wpdb->prepare( "SELECT AES_DECRYPT(UNHEX(%s),%s)", $input, $key ) );`

After this change you'll need to re-enter your password and save the settings.

Does this solve it for you?

**Comment by ToeiRei** [comment]
Fix applied. No joy.

```
20150424090440 - WP2D_Options->admin_options_page[class-options.php:117]
WP2D_API->init[class-options.php:117]
WP2D_API->_fetch_token[class-api.php:175]
WP2D_API->_http_request[class-api.php:195]
WP2D_Helpers::add_debugging[class-api.php:450]
code 200 on https://pusteblume.stargazer.at/users/sign_in
```

**Comment by noplanman** [comment]
Ok, the hunt continues then ;-)
Thanks for the update

**Comment by ToeiRei** [comment]
you're welcome.
Regarding the code 200 at the http protocol, I think it actually connects...but gets/sends an unexpected answer

**Comment by noplanman** [comment]
Ok, I've found the issue.

Replace the `token` regex in `lib/class-api.php` on line 119:
`'token' => '/content="(.*?)" name="csrf-token"|name="csrf-token" content="(.*?)"/',`

The problem here is, that some pods have the meta field attributes in a different order.

@ToeiRei Please give this another go. I've tested this on my side with your pod and it works. This fix will be included in the next release.
@gutobenn We should look for a cleaner solution to this, as parsing HTML with regex is not so pretty ;-)

**Comment by ToeiRei** [comment]
As far as I can see, I get aspects pulled in. (y) good job!

**Comment by schnied** [comment]
in the meantime i have wordpress 4.2
i've edited the two lines in lib/class-helpers.php  and one line in lib/class-api.php ...now, everything works fine :-)
thank you!

stefan

**Comment by gutobenn** [comment]
Thanks a lot, @noplanman! :)

Version 1.3.2 is now available. Check it out.

**Comment by ToeiRei** [comment]
Sorry for reopening: Last time publishing an article lead to "Failed to post to diaspora*: Not logged in." again...

**Comment by noplanman** [comment]
Have you re-entered your password and re-saved the settings?
Please let us know if that fixes it or not, thanks :-)

**Comment by ToeiRei** [comment]
It looks like it works from time to time. I cannot fully reproduce the issue.
