### ISSUE TITLE
Plugin does not send posts, if Apache runs in safe mode (curl problem)

### ISSUE THREAD

**Issue by ciubotaru** [gutobenn/wp-to-diaspora#5]
I tested the plugin on several installations of WP, down to version 3.2.1. The plugin successfully installs, connects to Diaspora pod, but in certain cases does not send posts. Apparently, the problem is in Apache web servers that run in safe mode (most shared hostings, I guess).

The log says:

    [06-Jan-2015 14:18:36] PHP Warning:  curl_setopt() [<a href='function.curl-setopt'>function.curl-setopt</a>]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in [...]/public_html/wp-content/plugins/wp-to-diaspora/class-diaspora.php on line 23
    [06-Jan-2015 14:18:37] PHP Notice:  Undefined offset:  1 in [...]/public_html/wp-content/plugins/wp-to-diaspora/class-diaspora.php on line 31

**Comment by gutobenn** [comment]
Could you test 6d5c3ce7fae97b252264be1802d601fd5f7f7039 on these servers?

**Comment by ciubotaru** [comment]
OK, I'll give it a run and inform you when I have results.

**Comment by gutobenn** [comment]
I've just tested it. It's working.

**Comment by Faldrian** [comment]
@gutobenn Is it possible to make a pull-request to my repo? So the lib stays up to date. :)

**Comment by gutobenn** [comment]
@Faldrian Sure! :)

**Comment by ciubotaru** [comment]
> I've just tested it. It's working.

I tried commit https://github.com/gutobenn/wp-to-diaspora/commit/6d5c3ce7fae97b252264be1802d601fd5f7f7039 and version [`1.2.3`](https://github.com/gutobenn/wp-to-diaspora/releases/tag/v.1.2.3), but neither worked. The plugin says connection OK, error log is clean, but the post is not reshared.

If you want to play with one of my test servers, let me know.

**Comment by gutobenn** [comment]
>If you want to play with one of my test servers, let me know.

I would like to. Send me an e-mail with server info. Thanks.

**Comment by ciubotaru** [comment]
Hello.

Here is access information for one of my test servers. It's on a shared
hosting, running Apache ver. 2.2.19 (Unix), PHP version 5.2.*, MySQL ver.
5.1.

Domain: shrimp.netau.net
Login page: http://shrimp.netau.net/wp-login.php
Username: admin
Password: myfriend

The website runs WP version 2.6.1. Please, do not upgrade it, it's for
testing. Other than that, feel free to install/delete/edit/reinstall your
plugin, change connection info, post anything etc.

Error log is: http://shrimp.netau.net/wp-content/debug.log

Best regards,

Vitalie Ciubotaru

P.S.: No illegal activity, please. I have other sites on that hosting. I
don't want to lose them :-)

**Comment by MagicFab** [comment]
I am using it on a website hosted on Dreamhost w/o issues, before this fix.
