### ISSUE TITLE
Option to strip images, or code to avoid double-posting images

### ISSUE THREAD

**Issue by lpar** [gutobenn/wp-to-diaspora#53]
For some reason I'm ending up with the image in each post being posted twice. e.g. see https://diasp.org/u/mathew for examples. I would like some way to avoid this.

The images are included in the body of the post via regular CommonMark code, not as "featured images".

**Comment by lpar** [comment]
A presumably related problem: I added a graphical banner to my site's theme, and now it's posting that with every post!

**Comment by gutobenn** [comment]
@lpar is it still happening?

**Comment by lpar** [comment]
Can't tell yet, the plugin has stopped working with an unrelated error.

**Comment by lpar** [comment]
Seems to be fixed.
