### ISSUE TITLE
Post original link

### ISSUE THREAD

**Issue by noplanman** [gutobenn/wp-to-diaspora#55]
Rename the option `Show "Posted at" link?` to `Post original link` and add an input field to customise the text to be posted, offering a few variables (`url` and `title`).

e.g.:
- "View the [link]original post[/link]"
- "Full post at: [link][url][/link]"
- "[link][title][/link]"

**Comment by gutobenn** [comment]
Related to #7 and #10.

**Comment by gutobenn** [comment]
We've decided to add a new filter ```wp2d_title_filter``` for that.

Usage for ```<h3>``` titles:
```			
add_filter( 'wp2d_title_filter', 
		function( $default, $link, $title ) {
				return sprintf('<p><h3><a href="%2$s" title="%1$s">%2$s</a></h3></p>', 
					$link, $title );
		}, 10, 3 
);
```
