### ISSUE TITLE
Improve pod selection

### ISSUE THREAD

**Issue by noplanman** [gutobenn/wp-to-diaspora#56]
Make the pod selection easier by having a fixed list of pods loaded from podupti.me (which can still be refreshed) and the option of adding a custom pod url.

**Comment by ciubotaru** [comment]
I'm not sure if I mentioned it before, but I created a small auxiliary plugin that automates this task: [on github](https://github.com/ciubotaru/diaspora-podlist-updater) or [in WP plugin directory](https://wordpress.org/plugins/diaspora-podlist-updater/). Feel free to use it, if you find it helpful.

**Comment by noplanman** [comment]
Yes, we are already using podupti.me to update the pods via AJAX, thanks :-)

I just feel that we can make the selection process more intuitive for the WP to diaspora* plugin, that's all.
