### ISSUE TITLE
YouTube embed in WP not represented in D* post

### ISSUE THREAD

**Issue by katrinleinweber** [gutobenn/wp-to-diaspora#6]
example: https://pod.geraspora.de/posts/3168264 vs. http://www.konscience.de/2015/01/ksl000-knowledge-communication-back-to-the-ears/

Assuming D* can't resolve YouTube embeds, it would be helpful if this plugin posted the bare URL to the video in question.

**Comment by gutobenn** [comment]
Done. That's very important. 
Thanks for reporting, @katrinleinweber :)
