### ISSUE TITLE
headings in D* post larger than title

### ISSUE THREAD

**Issue by katrinleinweber** [gutobenn/wp-to-diaspora#7]
Related to #6, please see examples there. Since the post title only appears as normal-sized, bold text, the bigger `<h3>References</h3>` below distracts a bit. Could the title please be treated as `<h1>`, or instead all headings from the WP post translated to bold text in D*?

**Comment by noplanman** [comment]
Treating the title as an `<h1>` tag probably makes more sense, as that way the general structure is preserved.
If for example somebody posts a longer article and all headings are converted to simple bold text, I can imagine it to be a bit difficult to navigate.

There's always the option of adding a setting, where one can choose the behaviour.

**Comment by gutobenn** [comment]
We've decided to add a new filter ```wp2d_title_filter``` for that.

Usage for ```<h3>``` titles:
```			
add_filter( 'wp2d_title_filter', 
		function( $default, $link, $title ) {
				return sprintf('<p><h3><a href="%2$s" title="%1$s">%2$s</a></h3></p>', 
					$link, $title );
		}, 10, 3 
);
```
