### ISSUE TITLE
indented list in WP not correctly flattened

### ISSUE THREAD

**Issue by katrinleinweber** [gutobenn/wp-to-diaspora#8]
And a 3rd one from #6, sorry!

This list
````
<ul>
	<li>normal list item
<ul>
	<li>indented item</li>
	<li>another one</li>
</ul>
</li>
	<li>normal item again</li>
</ul>
````
is shown as expected in WP:

- normal list item
 - indented item
 - another one
- normal item again

But as the following in D*:

- normal list item- indented item
- another one
- normal item again

**Comment by gutobenn** [comment]
Thank you for reporting, @katrinleinweber.
It's a bug on https://github.com/nickcernis/html-to-markdown. I will try to fix it or open an issue there.

**Comment by noplanman** [comment]
@gutobenn Is this issues resolved?

**Comment by gutobenn** [comment]
@noplanman  Not yet, but there has been a progress: https://github.com/thephpleague/html-to-markdown/issues/19

**Comment by noplanman** [comment]
Ok, hope it gets solved soon :blush:

**Comment by gutobenn** [comment]
Fixed :)

**Comment by katrinleinweber** [comment]
Merci :-)

**Comment by noplanman** [comment]
Nice! Thanks :smiley:
