### ISSUE TITLE
Fix tagging

### ISSUE THREAD

**Issue by lupa18** [gutobenn/wp-to-diaspora#82]
After make a new post I got a blank screen. 
Our installation is a Wordpress Mu and in this particular site test, wp-to-diaspora is not configured. 
WP Version:  4.3.1-es_ES

Apache error log: 
http://pastebin.com/t1DTFtsL

**Comment by noplanman** [comment]
Hi @lupa18 
We haven't looked into multisite installations yet.
Now that you have brought it up, the priority for it has just increased :wink: 
Thanks for reporting!

**Comment by noplanman** [comment]
The problem wasn't multisite related and has been fixed.

**Comment by noplanman** [comment]
@lupa18 Version 1.5.0 has been released yesterday, could you please give it a try and let us know if it is now working for you please? Thanks!

**Comment by lupa18** [comment]
Hello and thanks, 

It appear to be solved. It says: 
   Failed to post to diaspora*. Failed to initialize connection to pod "https://" 
what its true since is not configured for this site. 

The only issue now is the "ignore" link doesn't work; I had to use the cross at the right to clear the error message.
