### ISSUE TITLE
support custom posts

### ISSUE THREAD

**Issue by katrinleinweber** [gutobenn/wp-to-diaspora#9]
The WordPress instance (v4.1) I'm using this plugin on is mostly publishing custom posts ([Podlove](https://github.com/podlove/podlove-publisher/) Episodes). It already works well for regular posts, so removing that limitation would be :cake:

**Comment by noplanman** [comment]
Great idea. It might make sense to be able to choose which post types should allow posting to Diaspora*.
Maybe adding a section to the settings that lists all available post types, which can then be selected individually?

Also, the post types at least need to have a title and description.
If not, how would that be handled?

**Comment by katrinleinweber** [comment]
Podlove Episodes have (or at the very least encourage to use) well defined metadata, see #10. Default should IMHO only be title. A list of post types (if more than 1 is found) would indeed be helpful. By default, all should be selected IMHO.

**Comment by noplanman** [comment]
@katrinleinweber So you're suggesting to have a field where the "content" of the entry being posted to Diaspora* can be set up using meta data fields like the screenshot on #10?

Obviously this is also post type specific and would need a mechanism of saving different default posting options for each post type.

**Comment by katrinleinweber** [comment]
I haven't used more than the default and episode post type so far, so I'm not sure how much variability needs to be covered by an option for this. Presumably, all post types have titles as a common denominator, so there could be fall-backs.

For my use case, this plugin would be extremely helpful already, if it simply posted `[Title](link)`.

**Comment by gutobenn** [comment]
Thanks for this important suggestion, @katrinleinweber :)
