### ISSUE TITLE
Publishing when modifying with Broken Link Checker

### ISSUE THREAD

**Issue by SGallay** [gutobenn/wp-to-diaspora#91]
When I modify a link through the plug-in Broken Link Checker (https://wordpress.org/plugins/broken-link-checker/), it automatically republishes the story to diaspora*. I had about twenty old stories pushed to framasphere.org yesterday and that was quite embarrassing.

This has been a problem since 1.5 and is still doing so in 1.51.

**Comment by noplanman** [comment]
I've been trying to reproduce the problem but can't.
Could you please explain the steps that you are doing so that we can reproduce it?

**Comment by SGallay** [comment]
My Wordpress install has, among other things, the plugin Broken Link Checker installed.

When I see there is a fairly big amount of broken links, I go to the Broken Link Checker interface, check the link and, if needed, change them within that interface. This is when WP to diaspora republishes them.

Now, looking at it, what may happens is that publishes articles that were never pushed to diaspora* in the first place. My blog is fairly old, with about 2500 articles. I have the feeling that all these old posts have the "publish to diaspora*" box ticked by default and, when any change is done to them, publishing happens.

I use the latest version of all these plugins, ditto for my Wordpress install (4.3.1).

I hope this helps.

Le 1 octobre 2015 à 16:25, Armando Lüscher <notifications@github.com> a écrit :

I've been trying to reproduce the problem but can't.
Could you please explain the steps that you are doing so that we can reproduce it?

**Comment by noplanman** [comment]
Thanks for the explanation!
What you say makes perfect sense.
This will be fixed soon.

**Comment by gutobenn** [comment]
@SGallay, please check the new release (1.5.2).

**Comment by SGallay** [comment]
Hi!

Just did. It seems to be working fine, no more issues with old posts being published after modification in Broken Link Checker.

Thanks!
