### ISSUE TITLE
Failed to post to diaspora*. There seems to be a problem with your server's CA certificate bundle. <a href="#" class="open-help-tab" data-help-tab="ssl">Help</a> Ignore

### ISSUE THREAD

**Issue by lpar** [gutobenn/wp-to-diaspora#97]
I've placed [cacert.pem](http://curl.haxx.se/ca/cacert.pem) in wp-content/plugins/wp-to-diaspora.

(And the HTML appears verbatim in the error message.)

**Comment by noplanman** [comment]
Does your web user have the necessary rights to access the cacert.pem file?
Would it be possible for you to check your server error logs to see what the problem is?

**Comment by lpar** [comment]
Not sure what I did, if anything, but it's now working.

**Comment by noplanman** [comment]
Ok. Still needs fixing for the HTML in the error though, that's not cool ;-)
